int32 vgid
int8 is_valid
float32 system
float32 buffer_sz
float32 cache_sz
float32 heap_sz
float32 stack_sz
---
int32 vgid
float32 p_buffer
float32 p_cache
float32 p_heap
float32 p_stack
float32 p_intercept
